(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> <Set (auth_event.user_id = 12)> is not JSON serializable"
p3
sS'layer'
p4
S'/home/manohar/work/bisineer_store/web2py/applications/betastore/views/generic.json'
p5
sS'code'
p6
S"from gluon.serializers import json\nresponse.write(XML(json(response._vars)))\nresponse.write('\\n', escape=False)"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/manohar/work/bisineer_store/web2py/gluon/restricted.py", line 224, in restricted\n    exec ccode in environment\n  File "/home/manohar/work/bisineer_store/web2py/applications/betastore/views/generic.json", line 2, in <module>\n  File "/home/manohar/work/bisineer_store/web2py/gluon/serializers.py", line 124, in json\n    default=default).replace(ur\'\\u2028\',\n  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 296, in dumps\n    **kw).encode(obj)\n  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 226, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 296, in iterencode\n    return _iterencode(o, 0)\n  File "/home/manohar/work/bisineer_store/web2py/gluon/serializers.py", line 97, in custom_json\n    raise TypeError(repr(o) + " is not JSON serializable")\nTypeError: <Set (auth_event.user_id = 12)> is not JSON serializable\n'
p11
s.